version: "3"

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./db/log:/var/www/html/ZendSample/log
    ports:
      - 8080:80
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/db/init
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zend_db
      - MYSQL_USER=zend
      - MYSQL_PASSWORD=password