version: "3.8"

services:
  web:
    build: .
    container_name: web
    volumes:
      - ./src:/var/www/html
      - ./configs/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ./db/log:/var/www/html/todoapp/log
    ports:
      - 8080:80
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/db/init
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zend_db
      - MYSQL_USER=zend
      - MYSQL_PASSWORD=password
    tty: true
