<?php
// page title
$this->headTitle("Sign up");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <div class="container">
        <h1>Let's make your account.</h1>
    </div>
    <div class="container">
        <div class="d-grid gap-3 col-4 mx-auto">
            <form method="POST" action="/ZendSample/public/welcome/signup">
                <input class="form-control" type="email" placeholder="Email" name="user_email" ><br>
                <input class="form-control" type="password" placeholder="Password" name="user_password" ><br>
                <input class="btn btn-primary" type="submit" value="Sign up">
            </form>
        </div>
    </div>
</div>