<?php
// page title
$this->headTitle("Sign in");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <h1>This is the Sign-in page.</h1>
    <div>
        <form method="POST" action="/ZendSample/public/welcome/signin">
            <input type="email" placeholder="Email" name="user_email" ><br>
            <input type="password" placeholder="Password" name="user_password" ><br>
            <input type="submit" value="Sign in">
        </form>
        <p>Do you have no accounts?</p>
        <form method="GET" action="/ZendSample/public/welcome/signup">
            <input type="submit" value="Sign up">
        </form>
    </div>
</div>