<?php
// page title
$this->headTitle("Sign in");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/normalize.css");
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <div class="container page-title">
        <h1>This is the Sign-in page.</h1>
    </div>
    <div class="container form-container">
        <div class="d-grid gap-3 col-4 mx-auto">
            <form method="POST" action="/kanban/welcome/signin">
                <input class="form-control" type="email" placeholder="Email" name="<?= USER_EMAIL ?>" ><br>
                <input class="form-control" type="password" placeholder="Password" name="<?= USER_PASSWORD ?>" ><br>
                <input class="btn btn-primary" type="submit" value="Sign in">
            </form>
        </div>
    </div>
    <div class="container">
        <div>
            <p>Do you have no accounts?</p>
            <a class="btn btn-primary" href="/kanban/welcome/signup" role="button">Sign up</a>
        </div>
    </div>
</div>