<?php
// page title
$this->headTitle("Sign in");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <div class="container">
        <h1>This is the Sign-in page.</h1>
    </div>
    <div class="container">
        <div class="d-grid gap-3 col-4 mx-auto">
            <form method="POST" action="/ZendSample/public/welcome/signin">
                <input class="form-control" type="email" placeholder="Email" name="user_email" ><br>
                <input class="form-control" type="password" placeholder="Password" name="user_password" ><br>
                <input class="btn btn-primary" type="submit" value="Sign in">
            </form>
        </div>
    </div>
    <div class="container">
        <div>
            <p>Do you have no accounts?</p>
            <a class="btn btn-primary" href="/ZendSample/public/welcome/signup" role="botton">Sign up</a>
        </div>
    </div>
</div>