<?php
// page title
$this->headTitle("Home");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
// script
$this->headScript()->appendFile("/ZendSample/js/home/taskCard.js");
?>

<div class="content">
    <div class="container">
        <h1>This is your home.</h1>
    </div>
    <div class="container">
        <div class="d-grid gap-3 col-2 mx-auto">
            <a class="btn btn-primary" href="/ZendSample/public/welcome/signout" role="botton">Sign out</a>
            <a class="btn btn-primary" href="/ZendSample/public/home/newtask" role="botton">New task</a>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-start">
            <?php foreach($this->taskStatus as $status) { ?>
                <div class="col">
                <h2><?= $status ?></h2>
                <?php
                    foreach($this->allTasks as $task) {
                        if ($task->getTaskStatus() == $status) {
                ?>
                            <div class="card">
                                <div>
                                    <div class="card-body">
                                        <div class="card-title">
                                            <?= $task->getTaskTitle() ?>
                                        </div>
                                        <div class="card-text">
                                            <?= $task->getTaskContent() ?>
                                        </div>
                                        <div class="card-text">
                                            <?= $task->getTaskStatus() ?>
                                        </div>
                                    </div>
                                    <div class="d-grid col-1">
                                        <a
                                        class="btn btn-success btn-sm"
                                        data-bs-toggle="collapse"
                                        href="#id_<?= $task->getTaskId() ?>"
                                        role="button"
                                        aria-expanded="false"
                                        >
                                            Edit
                                        </a>
                                    </div>
                                    <div class="d-grid col-1">
                                        <form method="POST" action="/ZendSample/public/home/deletetask">
                                            <input type="hidden" name="<?= TASK_ID ?>" value="<?= $task->getTaskId() ?>">
                                            <input class="btn btn-secondary btn-sm" type="submit" value="Delete">
                                        </form>
                                    </div>
                                </div>
                                <!-- [START] Shown when 'Edit' button is pushed -->
                                <div class="collapse" id="id_<?= $task->getTaskId() ?>">
                                    <form method="POST" action="/ZendSample/public/home/updatetask">
                                        <input type="hidden" name="<?= TASK_ID ?>" value="<?= $task->getTaskId() ?>">
                                        <input class="form-control" type="text" name="<?= TASK_TITLE ?>" value="<?= $task->getTaskTitle() ?>" ><br>
                                        <input class="form-control" type="text" name="<?= TASK_CONTENT ?>" value="<?= $task->getTaskContent() ?>" ><br>
                                        <select class="form-select" name="<?= TASK_STATUS ?>">
                                            <option value="<?= TASK_TO_DO ?>" <?php if ($task->getTaskStatus() == $status) { ?>selected<?php } ?>><?= TASK_TO_DO ?></option>
                                            <option value="<?= TASK_IN_PROGRESS ?>" <?php if ($task->getTaskStatus() == $status) { ?>selected<?php } ?>><?= TASK_IN_PROGRESS ?></option>
                                            <option value="<?= TASK_DONE ?>" <?php if ($task->getTaskStatus() == $status) { ?>selected<?php } ?>><?= TASK_DONE ?></option>
                                        </select><br>
                                        <input class="btn btn-success" type="submit" value="Update">
                                    </form>
                                </div>
                                <!-- [END] Shown when 'Edit' button is pushed -->
                            </div>
                <?php
                        }              
                    }
                ?>
            </div>
            <?php } ?>
        </div>
    </div>
</div>