<?php
// page title
$this->headTitle("Home");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <div class="container">
        <h1>This is your home.</h1>
    </div>
    <div class="container">
        <div class="d-grid gap-3 col-2 mx-auto">
            <a class="btn btn-primary" href="/ZendSample/public/welcome/signout" role="botton">Sign out</a>
            <a class="btn btn-primary" href="/ZendSample/public/home/newtask" role="botton">New task</a>
        </div>
    </div>
    <div class="container">
        <div class="row align-items-start">
            <div class="col">
                <h2><?= TASK_TO_DO ?></h2>
                <?php
                    foreach($this->allTasks as $task) {
                        if ($task->getTaskStatus() == TASK_TO_DO) {
                ?>
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <?= $task->getTaskTitle() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskContent() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskStatus() ?>
                        </div>
                    </div>
                </div>
                <?php
                        }              
                    }
                ?>
            </div>
            <div class="col">
                <h2><?= TASK_IN_PROGRESS ?></h2>
                <?php
                    foreach($this->allTasks as $task) {
                        if ($task->getTaskStatus() == TASK_IN_PROGRESS) {
                ?>
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <?= $task->getTaskTitle() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskContent() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskStatus() ?>
                        </div>
                    </div>
                </div>
                <?php
                        }              
                    }
                ?>
            </div>
            <div class="col">
                <h2><?= TASK_DONE ?></h2>
                <?php
                    foreach($this->allTasks as $task) {
                        if ($task->getTaskStatus() == TASK_DONE) {
                ?>
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <?= $task->getTaskTitle() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskContent() ?>
                        </div>
                        <div class="card-text">
                            <?= $task->getTaskStatus() ?>
                        </div>
                    </div>
                </div>
                <?php
                        }              
                    }
                ?>
            </div>
        </div>
    </div>
</div>