<?php
// page title
$this->headTitle("Home");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <h1>Let me know your new task.</h1>
    <div>
        <form method="POST" action="/ZendSample/public/home/newtask">
            <input type="text" placeholder="Title" name="task_title" ><br>
            <input type="text" placeholder="Content" name="task_content" ><br>
            <input type="submit" value="Register">
        </form>
    </div>
    <div>
        <form method="GET" action="/ZendSample/public/home/index">
            <input type="submit" value="Back to home">
        </form>
    </div>
</div>