<?php
// page title
$this->headTitle("Home");
// header and footer
$this->assign("content_header", "common-header.phtml");
$this->assign("content_footer", "common-footer.phtml");
$this->assign("content_header_title", "Common Header");
$this->assign("content_footer_text", "Common Footer");
// stylesheet
$this->headLink()->appendStylesheet("/ZendSample/css/common-layout.css");
?>

<div class="content">
    <div class="container">
        <h1>Let me know your new task.</h1>
    </div>
    <div class="container">
        <div class="d-grid gap-3 col-4 mx-auto">
            <form method="POST" action="/ZendSample/public/home/newtask">
                <input class="form-control" type="text" placeholder="Title" name="task_title" ><br>
                <input class="form-control" type="text" placeholder="Content" name="task_content" ><br>
                <select class="form-select" name="<?= TASK_STATUS ?>">
                    <option value="<?= TASK_TO_DO ?>" selected><?= TASK_TO_DO ?></option>
                    <option value="<?= TASK_IN_PROGRESS ?>"><?= TASK_IN_PROGRESS ?></option>
                    <option value="<?= TASK_DONE ?>"><?= TASK_DONE ?></option>
                </select><br>
                <input class="btn btn-primary" type="submit" value="Register">
            </form>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="d-grid gap-3 col-2 mx-auto">
            <a class="btn btn-primary" href="/ZendSample/public/home/index" role="botton">Back to home</a>
        </div>
    </div>
</div>